# Generated by Django 6.0.6 on 2026-06-29 03:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='کد کالا')),
                ('name', models.CharField(max_length=100, verbose_name='نام کالا')),
                ('description', models.TextField(blank=True, default='', verbose_name='توضیحات')),
                ('shelf', models.CharField(blank=True, default='', max_length=50, verbose_name='قفسه')),
                ('manufacturer', models.CharField(blank=True, default='', max_length=100, verbose_name='تولیدکننده')),
                ('category', models.CharField(blank=True, default='', max_length=50, verbose_name='دسته\u200cبندی')),
                ('subcategory', models.CharField(blank=True, default='', max_length=50, verbose_name='زیر\u200cدسته')),
                ('unit', models.CharField(blank=True, default='عدد', max_length=20, verbose_name='واحد')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='موجودی')),
                ('min_stock', models.PositiveIntegerField(blank=True, default=0, verbose_name='حداقل موجودی')),
                ('location', models.CharField(blank=True, default='', max_length=100, verbose_name='مکان انبار')),
                ('last_price', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, verbose_name='آخرین قیمت خرید')),
                ('profit_margin', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, verbose_name='درصد سود')),
                ('shipping_cost', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, verbose_name='هزینه ارسال')),
                ('discount_percentage', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, verbose_name='درصد تخفیف')),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, verbose_name='قیمت فروش')),
                ('entry_date', models.DateField(blank=True, null=True, verbose_name='تاریخ ورود')),
                ('supplier_code', models.CharField(blank=True, default='', max_length=50, verbose_name='کد تأمین\u200cکننده')),
                ('image', models.URLField(blank=True, default='', verbose_name='تصویر')),
            ],
            options={
                'verbose_name': 'کالا',
                'verbose_name_plural': 'کالاها',
                'ordering': ['-code'],
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('login', 'ورود به سیستم'), ('logout', 'خروج از سیستم'), ('add_item', 'افزودن کالا'), ('edit_item', 'ویرایش کالا'), ('delete_item', 'حذف کالا'), ('transaction_in', 'ورود کالا'), ('transaction_out', 'خروج کالا'), ('create_invoice', 'ایجاد فاکتور'), ('edit_invoice', 'ویرایش فاکتور'), ('delete_invoice', 'حذف فاکتور'), ('add_user', 'ایجاد کاربر'), ('edit_user', 'ویرایش کاربر'), ('receive_invoice', 'دریافت فاکتور'), ('return_purchase', 'بازگشت به خرید')], max_length=20, verbose_name='نوع فعالیت')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ و زمان')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'فعالیت',
                'verbose_name_plural': 'فعالیت\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, db_index=True, max_length=50, unique=True, verbose_name='شماره فاکتور')),
                ('date', models.DateField(db_index=True, default=django.utils.timezone.now, verbose_name='تاریخ')),
                ('company_name', models.CharField(blank=True, default='', max_length=100, verbose_name='نام شرکت')),
                ('company_address', models.CharField(blank=True, default='', max_length=200, verbose_name='آدرس شرکت')),
                ('company_phone', models.CharField(blank=True, default='', max_length=20, verbose_name='تلفن شرکت')),
                ('total_amount', models.DecimalField(db_index=True, decimal_places=2, default=0.0, max_digits=10, verbose_name='مبلغ کل')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices_as_customer', to=settings.AUTH_USER_MODEL, verbose_name='مشتری')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices_created', to=settings.AUTH_USER_MODEL, verbose_name='ادمین')),
            ],
            options={
                'verbose_name': 'فاکتور',
                'verbose_name_plural': 'فاکتورها',
                'ordering': ['-number'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='تعداد')),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, verbose_name='قیمت واحد')),
                ('apply_profit', models.BooleanField(default=True, verbose_name='اعمال درصد سود')),
                ('apply_shipping', models.BooleanField(default=True, verbose_name='اعمال هزینه ارسال')),
                ('apply_discount', models.BooleanField(default=True, verbose_name='اعمال درصد تخفیف')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='warehouse.invoice', verbose_name='فاکتور')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.item', verbose_name='کالا')),
            ],
            options={
                'verbose_name': 'آیتم فاکتور',
                'verbose_name_plural': 'آیتم\u200cهای فاکتور',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'ادمین'), ('customer', 'مشتری')], default='customer', max_length=10, verbose_name='نقش')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پروفایل',
                'verbose_name_plural': 'پروفایل\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('in', 'ورود'), ('out', 'خروج')], max_length=3, verbose_name='نوع')),
                ('quantity', models.PositiveIntegerField(verbose_name='تعداد')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='تاریخ')),
                ('notes', models.TextField(blank=True, db_index=True, default='', verbose_name='یادداشت')),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, verbose_name='قیمت واحد')),
                ('supplier', models.CharField(blank=True, default='', max_length=100, verbose_name='تأمین\u200cکننده')),
                ('destination', models.CharField(blank=True, default='', max_length=100, verbose_name='مقصد')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.item', verbose_name='کالا')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'تراکنش',
                'verbose_name_plural': 'تراکنش\u200cها',
            },
        ),
    ]
